<?php

namespace Local\Seo;

use Bitrix\Main\Context;
use Bitrix\Main\Page\Asset;

class SeoManager
{
    private static $instance = null;
    private $jsonLdSchemas = [];

    /**
     * Singleton instance
     * @return SeoManager
     */
    public static function getInstance()
    {
        if (self::$instance === null) {
            self::$instance = new self();
        }
        return self::$instance;
    }

    private function __construct()
    {
        // Private constructor for singleton
    }

    /**
     * Initialize all SEO logic (Canonical + Meta handlers)
     */
    public static function init()
    {
        $instance = self::getInstance();
        $instance->setCanonical();

        // OG tags render is now called explicitly in header.php via AddBufferContent
    }

    /**
     * 1. Canonical URL Logic
     * Handles pagination, calculator suffixes, trailing slashes.
     */
    public function setCanonical()
    {
        global $APPLICATION;

        $request = Context::getCurrent()->getRequest();
        $protocol = $request->isHttps() ? "https" : "http";
        $serverName = defined('SITE_SERVER_NAME') && strlen(SITE_SERVER_NAME) > 0 ? SITE_SERVER_NAME : ($_SERVER['SERVER_NAME'] ?? '');

        // Get generic page URL without parameters
        $pageUrl = $APPLICATION->GetCurPage(false);
        $canonicalUrl = $pageUrl;

        // 1. Remove pagination (/page-N/)
        $canonicalUrl = preg_replace('#/page-\d+/?$#', '/', $canonicalUrl);

        // 2. Remove calculator suffix (/calculator-dohodnosti/)
        $canonicalUrl = preg_replace('#/calculator-dohodnosti/?$#', '/', $canonicalUrl);

        // 3. Normalize slashes
        $canonicalUrl = preg_replace('#/+#', '/', $canonicalUrl);

        // Ensure trailing slash if not root
        if ($canonicalUrl !== '/' && substr($canonicalUrl, -1) !== '/') {
            $canonicalUrl .= '/';
        }

        $fullCanonicalUrl = $protocol . '://' . $serverName . $canonicalUrl;

        // Add to head
        Asset::getInstance()->addString('<link rel="canonical" href="' . $fullCanonicalUrl . '">', true);
    }

    /**
     * 2. Open Graph & Twitter Cards Logic
     * Fallback to standard Title/Description if OG not set.
     * Fallback to default image if OG:IMAGE not set.
     */
    public function renderOpenGraph()
    {
        global $APPLICATION;
        $props = $APPLICATION->GetPagePropertyList();

        $output = "\n<!-- Open Graph & SEO generated by SeoManager -->\n";

        // --- PREPARE DATA ---

        // Title
        $ogTitle = $props['og:title'] ?? $props['OG:TITLE'] ?? '';
        if (empty($ogTitle)) {
            $ogTitle = $APPLICATION->GetPageProperty('title');
            if (empty($ogTitle)) {
                $ogTitle = $APPLICATION->GetTitle(false);
            }
        }

        // Description
        $ogDesc = $props['og:description'] ?? $props['OG:DESCRIPTION'] ?? '';
        if (empty($ogDesc)) {
            $ogDesc = $APPLICATION->GetPageProperty('description');
        }

        // Image
        $ogImage = $props['og:image'] ?? $props['OG:IMAGE'] ?? '';
        if (empty($ogImage)) {
            $protocol = Context::getCurrent()->getRequest()->isHttps() ? "https" : "http";
            $serverName = defined('SITE_SERVER_NAME') && strlen(SITE_SERVER_NAME) > 0 ? SITE_SERVER_NAME : ($_SERVER['SERVER_NAME'] ?? '');
            $ogImage = $protocol . '://' . $serverName . '/local/templates/main/assets/img/home/home_open-graph_image.png';
        }

        // URL
        $ogUrl = $props['og:url'] ?? $props['OG:URL'] ?? '';
        if (empty($ogUrl)) {
            $protocol = Context::getCurrent()->getRequest()->isHttps() ? "https" : "http";
            $serverName = defined('SITE_SERVER_NAME') && strlen(SITE_SERVER_NAME) > 0 ? SITE_SERVER_NAME : ($_SERVER['SERVER_NAME'] ?? '');
            $ogUrl = $protocol . '://' . $serverName . $APPLICATION->GetCurPage(false);
        }

        // Type
        $ogType = $props['og:type'] ?? $props['OG:TYPE'] ?? 'website';

        // --- RENDER ---

        // Open Graph
        $output .= '<meta property="og:title" content="' . htmlspecialchars($ogTitle) . '">' . "\n";
        $output .= '<meta property="og:description" content="' . htmlspecialchars($ogDesc) . '">' . "\n";
        $output .= '<meta property="og:image" content="' . htmlspecialchars($ogImage) . '">' . "\n";
        $output .= '<meta property="og:url" content="' . htmlspecialchars($ogUrl) . '">' . "\n";
        $output .= '<meta property="og:type" content="' . htmlspecialchars($ogType) . '">' . "\n";
        $output .= '<meta property="og:locale" content="ru_RU">' . "\n";

        // Twitter
        $output .= '<meta name="twitter:card" content="summary_large_image">' . "\n";
        $output .= '<meta name="twitter:title" content="' . htmlspecialchars($ogTitle) . '">' . "\n";
        $output .= '<meta name="twitter:description" content="' . htmlspecialchars($ogDesc) . '">' . "\n";
        $output .= '<meta name="twitter:image" content="' . htmlspecialchars($ogImage) . '">' . "\n";

        return $output;
    }

    /**
     * 3. Indexation Control (Robots)
     * Wrapper for setting robots meta tag
     */
    public static function setIndexation($value = 'index, follow')
    {
        global $APPLICATION;
        $APPLICATION->SetPageProperty('robots', $value);
    }

    /**
     * 4. JSON-LD Management
     */

    /**
     * Add a dynamic schema (e.g. from a component)
     * @param array $schema
     */
    public static function addJsonLdSchema($schema)
    {
        if (empty($schema))
            return;

        $instance = self::getInstance();

        // Use @type as key to avoid duplicates if needed, or just append
        $type = $schema['@type'] ?? 'unknown';
        $instance->jsonLdSchemas[] = $schema;
    }

    /**
     * Render all JSON-LD schemas
     * @return string
     */
    public static function getJsonLd()
    {
        $instance = self::getInstance();
        $schemas = $instance->jsonLdSchemas;

        // Auto-add Organization if not present
        if (!self::hasSchemaType($schemas, 'Organization')) {
            $schemas[] = self::getOrganizationSchema();
        }

        // Auto-add WebSite if not present
        if (!self::hasSchemaType($schemas, 'WebSite')) {
            $schemas[] = self::getWebSiteSchema();
        }

        $output = "";
        foreach ($schemas as $schema) {
            $output .= '<script type="application/ld+json">' . "\n";
            $output .= json_encode($schema, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT);
            $output .= "\n</script>\n";
        }

        return $output;
    }

    private static function hasSchemaType($schemas, $type)
    {
        foreach ($schemas as $schema) {
            if (isset($schema['@type']) && $schema['@type'] === $type) {
                return true;
            }
        }
        return false;
    }

    private static function getOrganizationSchema()
    {
        $protocol = Context::getCurrent()->getRequest()->isHttps() ? 'https' : 'http';
        $serverName = defined('SITE_SERVER_NAME') ? SITE_SERVER_NAME : $_SERVER['SERVER_NAME'];
        $siteUrl = $protocol . '://' . $serverName;

        return [
            '@context' => 'https://schema.org',
            '@type' => 'Organization',
            '@id' => $siteUrl . '/#org',
            'name' => 'GIS Mining',
            'url' => $siteUrl . '/',
            'logo' => $siteUrl . '/local/templates/main/assets/img/header/logo_header_white.png',
            'contactPoint' => [
                '@type' => 'ContactPoint',
                'telephone' => '+78007777798',
                'contactType' => 'sales',
                'areaServed' => 'RU',
                'availableLanguage' => 'ru'
            ],
            'sameAs' => [
                'https://www.facebook.com/gismining',
                'https://www.linkedin.com/company/gis-mining',
                'https://www.instagram.com/gismining',
                'https://www.threads.com/@gismining',
                'https://vk.com/gis_mining',
                'https://t.me/gismining',
                'https://vc.ru/id4624566',
                'https://ru.tradingview.com/u/GIS-Mining/#settings-profile',
                'https://dzen.ru/user/wz4h9o1t6gyei9xirsrwh20ctri'
            ]
        ];
    }

    private static function getWebSiteSchema()
    {
        $protocol = Context::getCurrent()->getRequest()->isHttps() ? 'https' : 'http';
        $serverName = defined('SITE_SERVER_NAME') ? SITE_SERVER_NAME : $_SERVER['SERVER_NAME'];
        $siteUrl = $protocol . '://' . $serverName;

        return [
            '@context' => 'https://schema.org',
            '@type' => 'WebSite',
            '@id' => $siteUrl . '/#website',
            'url' => $siteUrl . '/',
            'name' => 'GIS Mining',
            'publisher' => [
                '@id' => $siteUrl . '/#org'
            ],
            'potentialAction' => [
                '@type' => 'SearchAction',
                'target' => $siteUrl . '/search/?q={search_term_string}',
                'query-input' => 'required name=search_term_string'
            ]
        ];
    }
}
